# Generated by Django 3.0.3 on 2020-06-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imguploader', '0002_auto_20200210_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitions',
            name='status',
            field=models.CharField(default='draft', max_length=10),
        ),
    ]
