# Generated by Django 3.0.3 on 2020-06-19 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imguploader', '0003_competitions_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='url',
        ),
    ]
