# Generated by Django 3.0.3 on 2020-06-20 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imguploader', '0004_remove_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='photometa',
            name='comp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imguploader.Competitions'),
        ),
    ]
